inputDataDir: C:/Users/Janine.Heiser/Desktop/planning
socrata_client_config_fname: socrata_config.yaml
fourXFour: uqai-dcpf
dataset_base_url: https://data.sfgov.org/resource/
dataset_dev_phase_field: Open Dataset
email_config_fname: email_config.yaml
job_name: CPC_0001_Planning_Cases
log_dir:  C:\Users\Janine.Heiser\Desktop\planning\logs\
rejected_chunks_file: rejectedChunks.json
exception_logfile: exception_log.txt
files_regex: planning_cases+[0-9]+
#these params are examples- fill in your own info here!!!